import '../css/all.css'
import '../css/common.css'
import '../css/blog.css'
import '../css/owl.carousel.min.css'
import '../css/owl.theme.default.min.css'
import 'jquery'
import './waypoint'
import './counter-up'
import './lottie'
import './vanilla-tilt'
import 'owl.carousel'
import './common'
import { blogFiller } from './blog-data-fetch'
blogFiller();